# Generated by Django 3.2.25 on 2025-04-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navmain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('fire', 'Fire'), ('ems', 'EMS'), ('traffic', 'Traffic'), ('crime', 'Crime'), ('natural', 'Natural')], max_length=10),
        ),
    ]
